####
# GitLab CI
####

# Image
image: openjdk:11-jdk-oracle

# Cache
cache:
  key: gradle
  paths:
  - .gradle/wrapper
  - .gradle/caches

# Stages
stages:
- build
- publish

# Build
Assemble:
  stage: build
  script:
  - ./gradlew assemble

# Publish
Publish:
  stage: publish
  script:
  - ./gradlew bintrayUpload
  only:
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/
